// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ppedv.Hotelmanager.Data.EfCore;

#nullable disable

namespace ppedv.Hotelmanager.Data.EfCore.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20220310141119_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BuchungGast", b =>
                {
                    b.Property<int>("BuchungenId")
                        .HasColumnType("int");

                    b.Property<int>("GaesteId")
                        .HasColumnType("int");

                    b.HasKey("BuchungenId", "GaesteId");

                    b.HasIndex("GaesteId");

                    b.ToTable("BuchungGast");
                });

            modelBuilder.Entity("ppedv.Hotelmanager.Model.Buchung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Bis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modfied")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Von")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ZimmerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("ZimmerId");

                    b.ToTable("Buchungen");
                });

            modelBuilder.Entity("ppedv.Hotelmanager.Model.Gast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GebDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modfied")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gaeste");
                });

            modelBuilder.Entity("ppedv.Hotelmanager.Model.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modfied")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotel", (string)null);
                });

            modelBuilder.Entity("ppedv.Hotelmanager.Model.Zimmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnzBetten")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modfied")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stockwerk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Zimmer");
                });

            modelBuilder.Entity("BuchungGast", b =>
                {
                    b.HasOne("ppedv.Hotelmanager.Model.Buchung", null)
                        .WithMany()
                        .HasForeignKey("BuchungenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ppedv.Hotelmanager.Model.Gast", null)
                        .WithMany()
                        .HasForeignKey("GaesteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ppedv.Hotelmanager.Model.Buchung", b =>
                {
                    b.HasOne("ppedv.Hotelmanager.Model.Hotel", "Hotel")
                        .WithMany("Buchungen")
                        .HasForeignKey("HotelId");

                    b.HasOne("ppedv.Hotelmanager.Model.Zimmer", "Zimmer")
                        .WithMany("Buchungen")
                        .HasForeignKey("ZimmerId");

                    b.Navigation("Hotel");

                    b.Navigation("Zimmer");
                });

            modelBuilder.Entity("ppedv.Hotelmanager.Model.Zimmer", b =>
                {
                    b.HasOne("ppedv.Hotelmanager.Model.Hotel", "Hotel")
                        .WithMany("Zimmer")
                        .HasForeignKey("HotelId");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("ppedv.Hotelmanager.Model.Hotel", b =>
                {
                    b.Navigation("Buchungen");

                    b.Navigation("Zimmer");
                });

            modelBuilder.Entity("ppedv.Hotelmanager.Model.Zimmer", b =>
                {
                    b.Navigation("Buchungen");
                });
#pragma warning restore 612, 618
        }
    }
}
